#!/usr/bin/env python3
# coding: utf-8
import os
import sys
import json
import math
import datetime
import requests
import unidecode

__author__ = "Theo Massard <massar_t@etna-alternance.net"


BASE_URL = "https://citymapper.com/"
ENDPOINT = "api/7/journeys?start=FROM&end=TO&region_id=fr-paris"


def f_minutes(seconds: int) -> int:
    """Simply formats time(int) to minutes, rounding to ceil

    :param seconds The value to format in seconds

    :type seconds int

    :returns: The value of seconds formatted in seconds
    :rtype int

    """
    val = math.ceil(seconds / 60)
    return val


def get_params():
    """
    Collects and returns the environment variables as
    `lon%Clat` after formatting them.
    TODO Allow configuration to collect dynamically

    :return: tuple of string containing the formatted destination
    :rtype str, str

    """
    home = os.environ.get("MY_HOME", False)
    work = os.environ.get("WORK", False)

    if not home or not work:
        print("Missing informations about the destinations.", file=sys.stderr)
        sys.exit(1)

    if False:
        source = home
        dest = work
    else:
        source = work
        dest = home

    tr_source = source.replace(',', "%2C")
    tr_dest = dest.replace(',', "%2C")
    return tr_source, tr_dest


def make_url(source: str, destination: str) -> str:
    """Returns the formatted url for the request

    :param source The `from` location of the journey
    :param destination The `to` location of the journey (actual destination)

    :type source str
    :type destination str

    :return: the formatted URL to use for the request to the Citymapper API
    :rtype str

    """
    unformatted_url = BASE_URL + ENDPOINT
    formatted = unformatted_url.replace(
            "FROM", source).replace("TO", destination)
    return formatted


def make_request(url: str) -> str:
    """
    Requests the content of the formatted url
    and returns the content of the page

    :param url The url with the `GET` parameters embedded in

    :type url str

    :returns: content of the url request
    :rtype str

    """
    response = requests.get(url)
    content = response.content
    return unidecode.unidecode(content.decode('utf-8'))


def content_to_obj(content: str) -> dict :
    """Transforms the url's content to JSON object

    :param content The content of the page

    :type content str

    :returns: a JSON object containing the journeys
    :rtype JSON

    """
    obj = json.loads(content)
    return obj


def dt_to_s(s_time: str) -> str:
    """TODO: Simple function parsing a basic timestamp

    :param s_time The string to parse

    :type s_time str

    :returns: String reformatted
    :rtype str

    """
    splitted = s_time.split('-')
    try:
        year = s_time[:4]
        month = s_time[5:7]
        day = s_time[8:10]
        hour = s_time[11:13]
        minute = s_time[14:16]
        seconds = s_time[17:19]
        tmp = "%s/%s/%s %s:%s:%s" % (year, month, day, hour, minute, seconds)
        return tmp
    except IndexError:
        return s_time

def function(arg1):
    """TODO: Docstring for function.

    :arg1: TODO
    :returns: TODO

    """
    pass

def get_journey_info(journey: dict) -> dict:
    """Formats the JSON for easy display

    :param leg A dictionnary containing the leg's informations

    :type leg dict

    :returns: Another object, easier to display, about the leg
    :rtype dict

    """
    journey_info = dict()
    journey_info['journey_duration'] = f_minutes(journey['duration_seconds'])
    journey_info['walk_duration'] = f_minutes(journey['walk_seconds'])
    steps = []
    legs = journey['legs']

    for ele in legs:
        print(ele.keys())
        for e, v in ele.items():
            print(e, ": ", v)
        print()
        step = dict()
        mode = ele['mode']
        step['mode'] = mode
        if mode == 'transit':
            try:
                step['transp_name'] = ele['routes'][0]['display_name']
            except IndexError:
                step['transp_name'] = 'UKNOWN'
        step['start'] = dt_to_s(ele['departure_time'])
        step['end'] = dt_to_s(ele['arrival_time'])
        step['distance'] = ele.get('distance_meters', '')
        steps.append(step)

    print(journey_info)
    print(steps)
    sys.exit()


def main():
    src, dst = get_params()
    #print("test")
    url = make_url(src, dst)
    print("Requesting url: " + url)
    content = make_request(url)
    #print(content)
    ob = content_to_obj(content)
    for nbr, journey in enumerate(ob['journeys']):
        sys.stdout.write("Journey #%i " % nbr)
        get_journey_info(journey)


if __name__ == "__main__":
    main()
